#!/usr/bin/env python3
# Generates font.h (8x16 1bpp ASCII 32..126) for the video player OSD.
from PIL import Image, ImageDraw, ImageFont
font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 13)
rows = []
for c in range(32, 127):
  im = Image.new("L", (8, 16), 0)
  ImageDraw.Draw(im).text((0, 0), chr(c), font=font, fill=255)
  g = []
  for y in range(16):
    b = 0
    for x in range(8):
      if im.getpixel((x, y)) > 100:
        b |= 1 << x
    g.append(b)
  rows.append("  {" + ",".join("0x%02x" % v for v in g) + "},  // %r" % chr(c))
open("font.h", "w").write("// Generated by mkfont.py (DejaVu Sans Mono), LSB = leftmost pixel.\n"
  "static const uint8_t font8x16[95][16] = {\n%s\n};\n" % "\n".join(rows))
